# Site settings
title: TwisterJS
email: twisterjsapps@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  TwisterJS is an open source project with a goal of teaching tech to underprivileged children.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://TwisterJS.github.io" # the base hostname & protocol for your site
twitter_username: TwisterJS
github_username:  TwisterJS

# Build settings
markdown: kramdown
